mode = "exec"

[[process]]
type = "vm"
kvm = false
kernel = "../pkvm_setup/vms/debian-boot/vmlinuz"
initrd = "../pkvm_setup/vms/debian-boot/initrd.img"
append = 'earlycon root=/dev/vda2 systemd.run="/bin/bash /dev/vdb"'

[process.disk.vda]
format = "qcow2"
path = "../pkvm_setup/vms/disk_guest.img"

[process.disk.vdb]
format = "raw"
path = "install_helper.sh"

[process.9p.vm_runner]
path = "."
