name: Build docker images

on:
  push:
    branches: [ "master" ]

jobs:

  cerberus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'src/cerberus'
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: |
        cd src/cerberus
        make -f Makefile_docker release
        docker tag cerberus:release galoisinc/cerberus:release
    - name: Push the Docker image
      run: docker push galoisinc/cerberus:release
    - name: Log out
      run: docker logout

  opensut-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag galoisinc/opensut-base:latest
    - name: Push the Docker image
      run: docker push galoisinc/opensut-base:latest
    - name: Log out
      run: docker logout
