name: Docker Image CI

on:
  push:
    # branches:
    #   - 'main'

env:
  OPENSUT_BASE_IMAGE_ID: ghcr.io/galoisinc/verse-opensut/opensut-base:latest
  CERBERUS_HARDENED_IMAGE_ID: ghcr.io/galoisinc/verse-opensut/cn-hardened:1.3

jobs:
  opensut-base:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        echo "Building ${{env.OPENSUT_BASE_IMAGE_ID}}"
        docker build . --file Dockerfile --tag ${{env.OPENSUT_BASE_IMAGE_ID}}
    - name: Push the Docker image
      run: docker push ${{env.OPENSUT_BASE_IMAGE_ID}}

  hardened-cerberus:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
          git submodule update --init src/cerberus
          ls -l src/cerberus

    - name: Login to Iron Bank Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry1.dso.mil
        username: ${{ secrets.IRONBANK_USERNAME }}
        password: ${{ secrets.IRONBANK_TOKEN }}

    - name: Pull the hardended RedHat image
      run: |
        docker pull registry1.dso.mil/ironbank/redhat/ubi/ubi9:9.4
        docker images

    - name: Replace the regular RedHat image with the Iron Bank one
      run: |
        head src/cerberus/Dockerfile.redhat
        sed -i 's/redhat\/ubi9\:9\.4/registry1\.dso\.mil\/ironbank\/redhat\/ubi\/ubi9\:9\.4/g' src/cerberus/Dockerfile.redhat
        head src/cerberus/Dockerfile.redhat

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build multi-platform image
      uses: docker/build-push-action@v5
      with:
        context: src/cerberus
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{env.CERBERUS_HARDENED_IMAGE_ID}}
        file: src/cerberus/Dockerfile.redhat
        attests: type=sbom
        provenance: mode=max
        github-token: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}

  test-hardened-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
          git submodule update --init src/cerberus
          ls -l src/cerberus

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}

    - name: Run CN CI tests
      run: |
        cd src/cerberus
        docker pull ${{ env.CERBERUS_HARDENED_IMAGE_ID }}
        docker run -v $PWD:/work -w /work ${{ env.CERBERUS_HARDENED_IMAGE_ID }} bash tests/run-cn.sh
