name: Docker Image CI

on:
  push:

env:
  CERBERUS_IMAGE_NAME: cerberus:release
  OPENSUT_BASE_IMAGE_NAME: opensut-base:latest
  CERBERUS_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/${CERBERUS_IMAGE_NAME}
  OPENSUT_BASE_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/${OPENSUT_BASE_IMAGE_NAME}

jobs:

  # cerberus-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: false
  #   - name: Checkout Cerberus submodule
  #     run: git submodule update --init src/cerberus
  #   - uses: dorny/paths-filter@v3
  #     id: changes
  #     with:
  #       filters: |
  #         src:
  #           - 'src/cerberus/**'

  cerberus:
    runs-on: ubuntu-latest
    # Wait from the paths-filter to be completed before starting next-job
    # needs: cerberus-check
    # if: needs.cerberus-check.outputs.output1 == 'true'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Checkout Cerberus submodule
      run: git submodule update --init src/cerberus
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        echo "Building $CERBERUS_IMAGE_ID"
        cd src/cerberus
        make -f Makefile_docker release
        docker tag cerberus:release $CERBERUS_IMAGE_ID
    - name: Push the Docker image
      run: docker push $CERBERUS_IMAGE_ID
    - name: Log out
      run: docker logout

  opensut-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        echo "Building $OPENSUT_BASE_IMAGE_ID"
        docker build . --file Dockerfile --tag $OPENSUT_BASE_IMAGE_ID
    - name: Push the Docker image
      run: docker push $OPENSUT_BASE_IMAGE_ID
