name: Docker Image CI

on:
  push:

env:
  REGISTRY: ghcr.io
  CERBERUS_IMAGE_NAME: cerberus:release
  OPENSUT_BASE_IMAGE_NAME: opensut-base:latest

jobs:

  cerberus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
        path: src/pkvm_setup/vhost-device
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        cd src/cerberus
        make -f Makefile_docker release
        docker tag cerberus:release $REGISTRY/$CERBERUS_IMAGE_NAME
    - name: Push the Docker image
      run: docker push $REGISTRY/$CERBERUS_IMAGE_NAME
    - name: Log out
      run: docker logout

  opensut-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # with:
      #   submodules: true
      #   repository: podhrmic/verse-vhost-device
      #   token: ${{ secrets.VHOST_DEVICE_ACCESS_TOKEN }}
      #   path: src/pkvm_setup/vhost-device
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.VERSE_OPENSUT_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag galoisinc/opensut-base:latest
    - name: Push the Docker image
      run: docker push $REGISTRY/$OPENSUT_BASE_IMAGE_NAME
